---
- name: "Downloading CRDs and controller deployment"
  get_url:
    url: "{{ item.url }}"
    dest: "{{ mig_download_location }}/{{ item.name }}"
    mode: '777'
  with_items: "{{ mig_resources }}"

- name: "{{ title }} CRDs"
  k8s:
    state: "{{ state }}"
    src: "{{ mig_download_location }}/{{ item.name }}"
  with_items: "{{ mig_resources }}"


- name: "Removing CRDs and controller deployment files"
  file:
    path: "{{ mig_download_location }}/{{ item.name }}"
    state: absent
  with_items: "{{ mig_resources }}"