---
- name: "Generating download location for CRDs"
  set_fact:
    mig_download_location: "/tmp/{{ (999999999999999999999 | random | string + (lookup('pipe', 'date +%s%N'))) | to_uuid() }}"

- name: "Creating download directory for CRDs"
  file:
    path: "{{ mig_download_location }}"
    state: directory

- name: "Downloading CRDs and controller deployment"
  get_url:
    url: "{{ item.url }}"
    dest: "{{ mig_download_location }}/{{ item.name }}"
    mode: '777'
  with_items:
    - { name: "cluster.yaml", url: "{{ mig_crd_cluster }}" }
    - { name: "migration.yaml", url: "{{ mig_crd_migration }}" }
    - { name: "plan.yaml", url: "{{ mig_crd_plan }}" }
    - { name: "storage.yaml", url: "{{ mig_crd_storage }}" }
    - { name: "registry.yaml", url: "{{ mig_crd_registry }}" }

- name: "{{ title }} CRDs"
  k8s:
    state: "{{ state }}"
    src: "{{ mig_download_location }}/{{ item }}"
  with_items:
    - "cluster.yaml"
    - "migration.yaml"
    - "plan.yaml"
    - "storage.yaml"
    - "registry.yaml"

- name: "Removing CRDs and controller deployment files"
  file:
    path: "{{ mig_download_location }}"
    state: absent