---
- name: "{{ title }} CRs"
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', 'crs/v' + mig_controller_version + '/' + item) }}"
  with_items:
    - "mig-cluster-local.yaml.j2"
    - "cluster-remote.yaml.j2"
    - "sa-secret-remote.yaml.j2"
    - "mig-cluster-remote.yaml.j2"
    - "mig-storage-creds.yaml.j2"
    - "mig-storage.yaml.j2"
    - "mig-plan.yaml.j2"
    - "mig-migration.yaml.j2"