mig_namespace: mig
mig_download_location: "/tmp"

# CRDs 
mig_crd_cluster: https://raw.githubusercontent.com/fusor/mig-controller/master/config/crds/migration_v1alpha1_migcluster.yaml
mig_crd_migration: https://raw.githubusercontent.com/fusor/mig-controller/master/config/crds/migration_v1alpha1_migmigration.yaml
mig_crd_plan: https://raw.githubusercontent.com/fusor/mig-controller/master/config/crds/migration_v1alpha1_migplan.yaml
mig_crd_storage: https://raw.githubusercontent.com/fusor/mig-controller/master/config/crds/migration_v1alpha1_migstorage.yaml
mig_crd_registry: https://raw.githubusercontent.com/kubernetes/cluster-registry/master/cluster-registry-crd.yaml
# controller deployment
mig_controller_release: https://raw.githubusercontent.com/fusor/mig-controller/master/config/releases/latest/manifest.yaml


destroy: "{{ False if ACTION=='create' else True }}"
title: "{{ 'Creating' if not destroy else 'Removing' }}"
state: "{{ 'present' if not destroy else 'absent' }}"     # state of k8s resources


mig_resources:
  - { name: "cluster.yaml", url: "{{ mig_crd_cluster }}" }
  - { name: "migration.yaml", url: "{{ mig_crd_migration }}" }
  - { name: "plan.yaml", url: "{{ mig_crd_plan }}" }
  - { name: "storage.yaml", url: "{{ mig_crd_storage }}" }
  - { name: "registry.yaml", url: "{{ mig_crd_registry }}" }
  - { name: "controller.yaml", url: "{{ mig_crd_registry }}" }